services:

  frontend:
    image: hello-frontend
    container_name: frontend
    ports:
      - 5001:5001
    restart: unless-stopped

  backend:
    image: hello-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
