services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    image: hello-frontend:v2
    container_name: frontend
    ports:
      - 5001
    restart: unless-stopped

  backend:
    image: hello-backend
    container_name: backend
    ports:
      - 8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postpass
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  db:
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postpass
    container_name: db_postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
